FROM python:3.6.6-slim-stretch

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install --upgrade -r requirements.txt  &&  pip install -U scikit-learn

COPY 020_api 020_api 
COPY 010_model 010_model

EXPOSE 5000 5000

ENTRYPOINT [ "python3.6", "/020_api/flask_json_api.py" ]
# ENTRYPOINT [ "python3.6", "/020_api/prueba.py" ]

# scp -P 4444 -r C:\Users\soyperales\OneDrive\ModelDeployment\src carlos@localhost:/home/carlos
# sudo docker build -t model -f Dockerfile_model .
# sudo docker run -p 5000:5000 --name model model
